// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LogoRotateController from "./logo_rotate_controller"
application.register("logo-rotate", LogoRotateController)

import MapController from "./map_controller"
application.register("map", MapController)

import NavigationController from "./navigation_controller"
application.register("navigation", NavigationController)

import ReadmoreController from "./readmore_controller"
application.register("readmore", ReadmoreController)
